# Generated by Django 4.0.2 on 2022-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
