# Generated by Django 4.0.2 on 2022-03-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_url_short'),
        ('affiliate', '0004_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
