# Generated by Django 4.0.2 on 2022-03-24 01:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ArteCriollo', max_length=25)),
                ('logo', models.ImageField(default='/static/images/logo.png', upload_to='image/logo')),
                ('icon', models.ImageField(default='/static/images/logo.png', upload_to='image/icon')),
                ('email', models.EmailField(default='artecriollocuba@gmail.com', max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(default='+5351183924', max_length=11)),
                ('mobile', models.CharField(default='+5351183924', max_length=11)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/socialred/icon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/socialred/logo')),
                ('name', models.CharField(max_length=25)),
                ('name_user', models.CharField(max_length=25)),
                ('url', models.URLField(max_length=50)),
            ],
        ),
    ]
