# Generated by Django 4.0.2 on 2022-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ArteCriollo', max_length=25)),
                ('logo', models.ImageField(upload_to='image/logo')),
                ('icon', models.ImageField(upload_to='image/icon')),
                ('email', models.EmailField(default='artecriollocuba@gmail.com', max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(default='+5351183924', max_length=11)),
                ('mobile', models.CharField(default='+5351183924', max_length=11)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
