# Generated by Django 4.0.2 on 2022-03-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='image/socialred/icon')),
                ('logo', models.ImageField(upload_to='image/socialred/logo')),
                ('name', models.CharField(max_length=25)),
                ('name_user', models.CharField(max_length=25)),
                ('url', models.URLField(max_length=30)),
            ],
        ),
    ]
