# Generated by Django 4.0.2 on 2022-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialred',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
