# Generated by Django 4.0.2 on 2022-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='type',
            field=models.CharField(choices=[('ALL_USER_AUTHENTICATED', 'ALL_USER_AUTHENTICATED'), ('ONE_USER', 'ONE_USER'), ('ALL_USER', 'ALL_USER'), ('GROUP_USER', 'GROUP_USER')], max_length=22),
        ),
    ]
