# Generated by Django 4.0.2 on 2022-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_page_active_alter_notificationuser_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='type',
            field=models.CharField(choices=[('ALL_USER', 'ALL_USER'), ('ALL_USER_AUTHENTICATED', 'ALL_USER_AUTHENTICATED'), ('GROUP_USER', 'GROUP_USER'), ('ONE_USER', 'ONE_USER')], max_length=22),
        ),
    ]
