# Generated by Django 4.0.2 on 2022-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
