# Generated by Django 4.0.2 on 2022-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletteruser_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletteruser',
            options={'ordering': ['-subscribe', '-date_added']},
        ),
        migrations.AddField(
            model_name='newsletteruser',
            name='unsubscribe_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
