# Generated by Django 4.0.2 on 2022-03-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletteruser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='subscribe',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='unsubscribe_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
