# Generated by Django 4.0.2 on 2022-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletteruser_subscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
