# Generated by Django 4.0.2 on 2022-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_alter_newsletteruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='resubscribe_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletteruser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
