# Generated by Django 4.0.2 on 2022-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_user_recommended'),
        ('profile', '0006_profile_recommended_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_digital_products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
