# Generated by Django 4.0.2 on 2022-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_profile_affiliated_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ci',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'HOMBRE'), ('MUJER', 'MUJER'), ('OTRO', 'OTRO')], max_length=6, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Sobre ti'),
        ),
    ]
