# Generated by Django 4.0.2 on 2022-03-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='related_auction',
            field=models.ManyToManyField(blank=True, to='auction.Auction'),
        ),
    ]
