# Generated by Django 4.0.2 on 2022-03-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('auction', '0002_rename_owner_auction_user_auction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
