# Generated by Django 4.0.2 on 2022-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='aprobated',
            field=models.BooleanField(default=False),
        ),
    ]
