# Generated by Django 4.0.2 on 2022-03-31 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0004_auction_aprobated'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='purchused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='purchused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchused_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
