# Generated by Django 4.0.2 on 2022-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
