# Generated by Django 3.2.13 on 2022-06-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_userbid_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='related_auction',
            field=models.ManyToManyField(blank=True, related_name='_auction_auction_related_auction_+', to='auction.Auction'),
        ),
    ]
