# Generated by Django 3.2.13 on 2022-06-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, related_name='_blog_post_related_post_+', to='blog.Post'),
        ),
    ]
