# Generated by Django 4.0.2 on 2022-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(related_name='related_post', to='blog.Post'),
        ),
    ]
