# Generated by Django 4.0.2 on 2022-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_merchant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='aprobated',
            field=models.BooleanField(default=False),
        ),
    ]
