# Generated by Django 4.0.2 on 2022-03-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_address_apt_address_localidad_address_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['provincia', 'municipio'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('P', 'Particular'), ('E', 'Envio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.municipio'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.pais'),
        ),
        migrations.AlterField(
            model_name='address',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.provincia'),
        ),
    ]
