# Generated by Django 4.0.2 on 2022-02-27 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_productimagescontent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagescontent',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_content', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimagescontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
