# Generated by Django 4.0.2 on 2022-03-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='products/content-files/'),
        ),
    ]
