# Generated by Django 4.0.2 on 2022-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_first_name_order_last_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='select_shiping_address',
            field=models.BooleanField(default=False),
        ),
    ]
