# Generated by Django 4.0.2 on 2022-02-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimagescontent_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimagescontent',
            name='product',
        ),
    ]
