# Generated by Django 4.0.2 on 2022-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_url_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_short',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
