# Generated by Django 4.0.2 on 2022-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
