# Generated by Django 4.0.2 on 2022-03-29 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_alter_product_url_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_recommended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommended', to=settings.AUTH_USER_MODEL),
        ),
    ]
