# Generated by Django 4.0.2 on 2022-03-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_email_order_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='select_shiping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
    ]
