# Generated by Django 4.0.2 on 2022-03-11 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_address_select_shiping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
