# Generated by Django 4.0.2 on 2022-03-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_whishlist', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='whishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whishlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
