# Generated by Django 4.0.2 on 2022-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('ENZONA', 'ENZONA'), ('TRANSFERMOVIL', 'TRANSFERMOVIL')], default='CASH', max_length=25),
        ),
    ]
