# Generated by Django 4.0.2 on 2022-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_whishlist_title_alter_whishlist_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
