# Generated by Django 4.0.2 on 2022-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('ENZONA', 'ENZONA'), ('TRANSFERMOVIL', 'TRANSFERMOVIL')], default='EFECTIVO', max_length=25),
        ),
    ]
