# Generated by Django 4.0.2 on 2022-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_options_product_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
