# Generated by Django 4.0.2 on 2022-05-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_category_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_lottery',
            field=models.BooleanField(default=False),
        ),
    ]
