# Generated by Django 4.0.2 on 2022-03-14 21:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, max_length=25, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/merchant')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/merchant')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/merchant')),
                ('description', ckeditor.fields.RichTextField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=125, null=True)),
                ('status', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.merchant'),
        ),
    ]
