# Generated by Django 4.0.2 on 2022-05-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_for_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ENTREGA_A_DOMICILIO', 'ENTREGA_A_DOMICILIO'), ('RECOGIDA_LOCAL', 'RECOGIDA_LOCAL')], default='ENTREGA_A_DOMICILIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('ENZONA', 'ENZONA'), ('TRANSFERMOVIL', 'TRANSFERMOVIL')], default='EFECTIVO', max_length=13),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('ENZONA', 'ENZONA'), ('TRANSFERMOVIL', 'TRANSFERMOVIL')], max_length=20),
        ),
    ]
