# Generated by Django 4.0.2 on 2022-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avialable_colours',
            field=models.ManyToManyField(blank=True, to='shop.ColorVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='avialable_sizes',
            field=models.ManyToManyField(blank=True, to='shop.SizeVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
