# Generated by Django 4.0.2 on 2022-03-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_avialable_colours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='colour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.colorvariation'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sizevariation'),
        ),
    ]
