# Generated by Django 4.0.2 on 2022-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_municipio_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[(1, 'DOMICILIO'), (2, 'RECOGIDA_LOCAL')], default=1, max_length=20),
        ),
    ]
