# Generated by Django 4.0.2 on 2022-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='map_langitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
