# Generated by Django 4.0.2 on 2022-06-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_address_map_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='pais',
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shipping', models.IntegerField(blank=True, default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.provincia')),
            ],
        ),
    ]
