# Generated by Django 4.0.2 on 2022-06-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_municipio_pais_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.localidad'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.municipio'),
        ),
    ]
