# Generated by Django 4.0.2 on 2022-06-04 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0021_alter_address_localidad_alter_localidad_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount', models.IntegerField(default=0)),
                ('discount_porcent', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finished', models.DateTimeField()),
                ('consumers', models.ManyToManyField(blank=True, related_name='consumers', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(blank=True, to='shop.Order')),
                ('products', models.ManyToManyField(blank=True, to='shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
