# Generated by Django 4.0.2 on 2022-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=models.CharField(default='CUBA', max_length=50),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
