# Generated by Django 4.0.2 on 2022-06-07 20:11

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
