# Generated by Django 4.0.2 on 2022-06-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_localidad_name_alter_municipio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
