# Generated by Django 3.2.13 on 2022-06-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_localidad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagescontent',
            name='title',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_shop_product_related_products_+', to='shop.Product'),
        ),
    ]
