# Generated by Django 4.0.2 on 2022-03-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_peoplelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleList',
        ),
    ]
