# Generated by Django 4.0.2 on 2022-03-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_slug'),
        ('authy', '0003_delete_peoplelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whishlist',
            field=models.ManyToManyField(blank=True, related_name='whishlist_user', to='shop.Product'),
        ),
    ]
