# Generated by Django 4.0.2 on 2022-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_category_order_discount_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
