# Generated by Django 4.0.2 on 2022-02-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(blank=True, choices=[('NO PAGADO', 'NO PAGADO'), ('AUTORIZADO', 'AUTORIZADO'), ('PAGADO', 'PAGADO'), ('ANULADO', 'ANULADO')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CONFIRMADO', 'CONFIRMADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('ANULADO', 'ANULADO')], max_length=15, null=True),
        ),
    ]
