# Generated by Django 4.0.2 on 2022-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_pay_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/category'),
        ),
    ]
