# Generated by Django 4.0.2 on 2022-02-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
