# Generated by Django 4.0.2 on 2022-05-28 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('count', models.IntegerField(default=0, verbose_name='Número de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Estadísticas de visitas diarias al sitio web',
                'verbose_name_plural': 'Estadísticas de visitas diarias al sitio web',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='Dirección IP')),
                ('count', models.IntegerField(default=0, verbose_name='Visitas')),
            ],
            options={
                'verbose_name': 'Acceder a la información del usuario',
                'verbose_name_plural': 'Acceder a la información del usuario',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Total de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Total de visitas al sitio web',
                'verbose_name_plural': 'Total de visitas al sitio web',
            },
        ),
    ]
