# Generated by Django 4.0.2 on 2022-06-02 03:48

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_somelocationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somelocationmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [23.07959345783162, -82.33867744659756], 'marker_color': 'blue'}),
        ),
    ]
