# Generated by Django 4.0.2 on 2022-06-02 05:43

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_alter_somelocationmodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Some2LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map')),
                ('location1', mapbox_location_field.models.LocationField(map_attrs={'center': [-82.38304, 23.13302], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'id': 'unique_id_1', 'language': 'auto', 'marker_color': 'blue', 'message_404': 'Dirección no definida', 'navigation_buttons': True, 'placeholder': 'Elija una ubicación en el mapa a continuación', 'readonly': True, 'rotate': False, 'style': 'mapbox://styles/mapbox/outdoors-v11', 'track_location_button': True, 'zoom': 10})),
                ('location2', mapbox_location_field.models.LocationField(map_attrs={'center': [-82.38304, 23.13302], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'id': 'unique_id_2', 'language': 'auto', 'marker_color': 'blue', 'message_404': 'Dirección no definida', 'navigation_buttons': True, 'placeholder': 'Elija una ubicación en el mapa a continuación', 'readonly': True, 'rotate': False, 'style': 'mapbox://styles/mapbox/outdoors-v11', 'track_location_button': True, 'zoom': 10})),
                ('address1', mapbox_location_field.models.AddressAutoHiddenField(map_id='unique_id_1')),
                ('address2', mapbox_location_field.models.AddressAutoHiddenField(map_id='unique_id_2')),
            ],
        ),
    ]
