# Generated by Django 4.0.2 on 2022-06-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_some2locationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Some2LocationModel',
        ),
    ]
