# Generated by Django 4.0.2 on 2022-05-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_product_for_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_finish', models.DateTimeField()),
                ('price_lottery', models.FloatField(default=0.0, verbose_name='Monto de inscripción')),
                ('value_product_lottery', models.FloatField(default=0.0, verbose_name='Valor del producto en el mercado(info)')),
                ('note', models.TextField(blank=True, null=True)),
                ('aprobated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('total_winners', models.IntegerField(default=1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('related_lottery', models.ManyToManyField(blank=True, to='lottery.Lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(blank=True, related_name='winners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('purchused', models.BooleanField(default=False)),
                ('transaction_uuid', models.CharField(max_length=32)),
                ('user_uuid', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('winner', models.BooleanField(default=False)),
                ('participant_number', models.IntegerField(blank=True)),
                ('lottery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.lottery')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery.participantpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
