# Generated by Django 4.0.2 on 2022-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
