# Generated by Django 4.0.2 on 2022-05-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lottery'),
        ),
    ]
