# Generated by Django 4.0.2 on 2022-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_participant_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
