# Generated by Django 4.0.2 on 2022-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_participant_participant_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_number',
            field=models.IntegerField(blank=True),
        ),
    ]
