# Generated by Django 4.0.2 on 2022-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_alter_lottery_price_lottery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='price_lottery',
            field=models.IntegerField(default=0, verbose_name='Monto de inscripción'),
        ),
    ]
