# Generated by Django 4.0.2 on 2022-05-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('send_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('send_users', models.ManyToManyField(blank=True, related_name='send_emails_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
